### PR TITLE
XIVY-14079 Fix buggy sidebar

### PR DESCRIPTION
**Pull request by ivy-lli**
https://1ivy.atlassian.net/browse/XIVY-14121

### CODE REVIEW

**Review by ivy-rew — APPROVED** [review]
surely good to have strictly-defined IDs, but why does this solve any bugs?

**Comment by ivy-lli** [comment]
> surely good to have strictly-defined IDs, but why does this solve any bugs?

because freya hold the current selected menu item inside a cookie, and if this id can change between renders, it can happen that the wrong element will be selected in the menu. If this ID's are fixed this should not happen.

**Comment by ivy-rew** [comment]
> > surely good to have strictly-defined IDs, but why does this solve any bugs?
> 
> because freya hold the current selected menu item inside a cookie, and if this id can change between renders, it can happen that the wrong element will be selected in the menu. If this ID's are fixed this should not happen.

ahh, good to know. thanks for sharing :+1:

**Review by ivy-edp — COMMENTED** [review]
Nice, thanks 👍

**Pull request merged**
