### PR TITLE
Raising project-build-plugin version to 10.0.6 / 10.0.7-SNAPSHOT

### PR DESCRIPTION
**Pull request by ivy-team**
Raising project-build-plugin version to 10.0.6 / 10.0.7-SNAPSHOT

### CODE REVIEW

**Comment by ivy-lli** [comment]
Hi @ivy-rew 
Do need the demo-projects on a release branch a released project-build-plugin or is this automatically switched to it when we trigger a new release?

**Comment by ivy-rew** [comment]
> Hi @ivy-rew Do need the demo-projects on a release branch a released project-build-plugin or is this automatically switched to it when we trigger a new release?

I'm unaware of any automated triggers, that are changing the project-build-plugin in here. But doesn't have to mean anything :)
I just see that under `.ivy/raise-build-plugin-version.sh` the change of the version can be triggered.

**Comment by ivy-lli** [comment]
I know that we use the snapshot version on the latest master for the snapshot release, but I think it needs to be a released project-build-plugin for a real release

**Comment by alexsuter** [comment]
> > Hi @ivy-rew Do need the demo-projects on a release branch a released project-build-plugin or is this automatically switched to it when we trigger a new release?
> 
> I'm unaware of any automated triggers, that are changing the project-build-plugin in here. But doesn't have to mean anything :) I just see that under `.ivy/raise-build-plugin-version.sh` the change of the version can be triggered.
> 
> maybe @alexsuter has a clue. thinking

Wäre hier definiert
https://github.com/axonivy/github-repo-manager/blob/master/build/raise-build-plugin-version/raise.sh

**Comment by ivy-rew** [comment]
> I know that we use the snapshot version on the latest master for the snapshot release, but I think it needs to be a released project-build-plugin for a real release

ahh yes indeed, that a restriction enforced by every maven release pipeline.

**Pull request merged**
