### PR TITLE
XIVY-8699 Run docker image before test to make sure service is online

### PR DESCRIPTION
**Pull request by jackra1n**

### CODE REVIEW

**Review by ivy-rew — APPROVED** [review]
finally green builds tomorrow? Thanks :love_letter:

**Review by alexsuter — CHANGES_REQUESTED** [review]
Thanks for this, would love to see that on all release branches, so we can stop the service on test-webservices.ivyteam.io

But:
- you just call docker from sh, and you don't ensure that the container is properly cleaned up. at least the cleanup statements must be in a finally block. But I don't like the mix of managing some containers in SH and the others with the "docker" command. so please convert this to the docker api.
- this solution is not github ready and also needs addtiional effor when executing in junit. is it not possible to start a simple web server in junit for this?

**Comment by alexsuter** [comment]
all right

**Comment by alexsuter** [comment]
furthermore this change will make port occupation. you can not run buidls in parallel on same node. please run the container in the given docker network and calling this service with the name of the container instead of localhost.

**Comment by alexsuter** [comment]
I see that this build has anyway problem with port occupation, driven by non-configurable port of the axon ivy engine in the project-build-plugin. I think you don't need to expose the port and participate in the same network -> "network --host"

I won't change the port to something else.

**Comment by jackra1n** [comment]
Hi @alexsuter, I tried without `--network host` but unfortunatelly it does not want to connect then

**Comment by alexsuter** [comment]
you can not use localhost

you need to use the name of the container

**Comment by jackra1n** [comment]
I had to make a small hack in `WebTestRestProcessStarts`
I think there might be a better solution that I don't know yet, so maybe we should look at it together in that case @alexsuter

**Comment by alexsuter** [comment]
you can get rid of the hack if you use configurstion overriding via java system properties.

remove the environment, pass the uri as java system property with the correct name.

**Comment by alexsuter** [comment]
something like

ivy.applicstions.anyyyy.RestClients.xxx.Url

**Comment by alexsuter** [comment]
hmm this may solves another problem. I'll will check this next week

**Review by alexsuter — APPROVED** [review]

**Comment by ivy-rew** [comment]
great to see this change coming; please consider to add it in a compliant way to release/10 likewise :-)

**Pull request merged**
