### PR TITLE
XIVY-7516 Fix deprecation warning on Ivy.wf().getApplication()

### PR DESCRIPTION
**Pull request by weissreto**

### CODE REVIEW

**Review by alexsuter — APPROVED** [review]
👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏

**Review by ivy-lli — APPROVED** [review]
Also ok for me 😉👌

**Comment by ivy-rew** [comment]
merge @weissreto

**Comment by ivy-lli** [comment]
@ivy-rew first he should add a suppress warning to the LazyDataModel7 deprecation warnings

**Comment by ivy-rew** [comment]
on master, yes @ivy-lli . This one here seem only targeting release/8.0 so it looks good as is to me.

**Comment by ivy-lli** [comment]
ah you're right, sorry

**Pull request merged**
